export const SOURCE_FIELD_KEY = {
  ACCESS: "Access",
  CONSENT_CODE: "Consent Code",
  CONSORTIUM: "Consortium",
  DATA_TYPE: "Data Type",
  DB_GAP_ID: "dbGap Id",
  DISEASE: "Disease",
  PARTICIPANTS: "Participants",
  SAMPLES: "Samples",
  SIZE_TB: "Size (TB)",
  STUDY: "Study",
  STUDY_ACCESSION: "Study Accession",
  STUDY_DESIGN: "Study Design",
  TERRA_WORKSPACE_NAME: "Terra Workspace Name",
};

export const SOURCE_FIELD_TYPE = {
  ACCESS: "string",
  CONSENT_CODE: "string",
  CONSORTIUM: "string",
  DATA_TYPE: "string",
  DB_GAP_ID: "string",
  DISEASE: "string",
  PARTICIPANTS: "number",
  SAMPLES: "number",
  SIZE_TB: "number",
  STUDY: "string",
  STUDY_ACCESSION: "string",
  STUDY_DESIGN: "string",
  TERRA_WORKSPACE_NAME: "string",
};
