# docker build -t explorer-nginx -f Dockerfile.nginx .
# docker run -p 3000:3000 explorer-nginx

# Install dependencies only when needed
FROM --platform=linux/amd64 nginx:mainline-alpine AS nginx
WORKDIR /app

COPY out/ /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/nginx.conf

#/usr/share/nginx/html/

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]